/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3d3zejqdjvftrbemye7riu5ccu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pmr3v3jrlzhtzh7np7igmb2lta",
    "aws_cognito_identity_pool_id": "us-east-1:a2c8aca3-24a7-4e5f-8d8f-6ab01002d16c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aP8UhKfIm",
    "aws_user_pools_web_client_id": "146iud94sakapc4anuck7u85th",
    "oauth": {},
    "aws_mobile_analytics_app_id": "42d6573beb344a15a9da55d6f91f0ac3",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "PremonDynamo-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
